---
title: "Final Neoantigen Prediciton Code"
author: "Maddy"
date: "2026-10-09"
output: html_document 
---
## Environment and Tool Setup

# Load miniconda
module load miniconda3/25.3.1

# Create mouse_env with fastp 
conda create -n mouse_env -c bioconda -c conda-forge fastp  -y
conda init bash
conda activate mouse_env

# Install GATK and BWA into mouse_env
conda install -c bioconda gatk4 bwa -y

# Install STAR and StringTie into mouse_env
conda install -c bioconda star -y
conda install -c bioconda stringtie -y

# Install readcount tools into mouse_env
conda install -c bioconda vt bam-readcount -y
pip install cyvcf2

# Install samtools into mouse_env
# (already available - version 1.20)

# Create and set up vep_env
conda create -n vep_env -c bioconda -c conda-forge ensembl-vep=115 -y
conda activate vep_env

# Download VEP cache for mouse GRCm39
vep_install -a cf -s mus_musculus -y GRCm39 -c $HOME/.vep --CONVERT

# Create pvac_env
conda create -n pvac_env -y
conda activate pvac_env
# Install pVACtools
pip install pvactools==5.2.0
pip install --force-reinstall numpy==1.24.4 pandas==2.0.3

# Install VEP plugins for pVACseq
conda activate pvac_env
pvacseq install_vep_plugin $HOME/.vep/Plugins

# Create vatools_env
conda create -n vatools_env python=3.9 -y
conda activate vatools_env
pip install vatools


## Resources:
### SSM3 Tumour and TAC239 WGS Data 

# SRA Project: SRRP061941
fasterq-dump SRR2142076
fasterq-dump SRR2141680
# Renamed 
mv SRR2142076_1.fastq  SSM3_1.fastq 
mv SRR2142076_2.fastq  SSM3_2.fastq
mv SRR2141680_1.fastq  TAC239_1.fastq
mv SRR2141680_2.fastq  TAC239_2.fastq 

### SSM3 RNA-Seq Data 

# # GEO: GSE268752, Sample: GSM8298412, SRA: SRX24763613
fasterq-dump --split-files SRR29245256
# Renamed
mv SRR29245256_1.fastq SSM3_RNA_1.fastq
mv SRR29245256_2.fastq SSM3_RNA_2.fastq


## Whole Genome Sequence 
### Quality Control

conda activate mouse_env

# SSM3 (tumour)
fastp \
    -i SSM3_1.fastq \
    -I SSM3_2.fastq \
    -o SSM3_1_clean.fastq \
    -O SSM3_2_clean.fastq \
    -h SSM3_fastp.html \
    -j SSM3_fastp.json

# TAC239 (germline)
fastp \
    -i TAC239_1.fastq \
    -I TAC239_2.fastq \
    -o TAC239_1_clean.fastq \
    -O TAC239_2_clean.fastq \
    -h TAC239_fastp.html \
    -j TAC239_fastp.json

### Download Reference Genome & Index

# Download GRCm39 reference genome (Ensembl release 115)
wget https://ftp.ensembl.org/pub/release-115/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa.gz

# Index for BWA alignment
bwa index Mus_musculus.GRCm39.dna_sm.primary_assembly.fa.gz

### BWA Alignment

# TAC239 germline alignment (2 threads)
bwa mem -t 2 \
    -R "@RG\tID:TAC239\tSM:TAC239\tPL:ILLUMINA\tLB:lib1" \
    ../Mouse-Resources/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa.gz \
    TAC239_1_clean.fastq TAC239_2_clean.fastq > TAC239.sam

# SSM3 tumour alignment (3 threads)
bwa mem -t 3 \
    -R "@RG\tID:SSM3\tSM:SSM3\tPL:ILLUMINA\tLB:lib1" \
    ../Mouse-Resources/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa.gz \
    SSM3_1_clean.fastq SSM3_2_clean.fastq > SSM3.sam

### Convert SAM to BAM and Index

# TAC239
samtools view -bS -@ 8 TAC239.sam | samtools sort -@ 8 -o TAC239_sorted.bam
samtools index -@ 8 TAC239_sorted.bam

# SSM3
samtools view -bS -@ 16 SSM3.sam | samtools sort -@ 16 -o SSM3_sorted.bam
samtools index -@ 8 SSM3_sorted.bam

### Mark Duplicates

# TAC239 germline
gatk MarkDuplicates -I TAC239_sorted.bam -O TAC239_markdup.bam -M TAC239_markdup_metrics.txt
samtools index -@ 8 TAC239_markdup.bam

# SSM3 tumour
gatk MarkDuplicates -I SSM3_sorted.bam -O SSM3_markdup.bam -M SSM3_markdup_metrics.txt
samtools index -@ 16 SSM3_markdup.bam

### Alignment Statistics 

samtools flagstat TAC239_markdup.bam > TAC239_alignment_stats.txt
samtools flagstat SSM3_markdup.bam > SSM3_alignment_stats.txt

### Reference Genome Preperation for GATK

# Decompress reference (keeping original)
Gunzip -c Mus_musculus.GRCm39.dna_sm.primary_assembly.fa.gz > Mus_musculus.GRCm39.dna_sm.primary_assembly.fa

# Index reference FASTA
samtools faidx Mus_musculus.GRCm39.dna_sm.primary_assembly.fa

# Create sequence dictionary
gatk CreateSequenceDictionary -R Mus_musculus.GRCm39.dna_sm.primary_assembly.fa.gz

### Somatic Variant Calling

# Call somatic variants with Mutect2
gatk Mutect2 \
    -R ../Mouse-Resources/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa \
    -I SSM3_markdup.bam \
    -I TAC239_markdup.bam \
    -tumor SSM3 \
    -normal TAC239 \
    -O somatic_variants.vcf.gz

# Apply statistical filters
gatk FilterMutectCalls \
    -R ../Mouse-Resources/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa \
    -V somatic_variants.vcf.gz \
    -O somatic_variants_filtered.vcf.gz

# Extract PASS variants
gatk SelectVariants \
    -R ../Mouse-Resources/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa \
    -V somatic_variants_filtered.vcf.gz \
    --exclude-filtered \
    -O somatic_variants_pass.vcf.gz

# Count PASS variants
gatk CountVariants -V somatic_variants_pass.vcf.gz
# Result: 57,996
# Count Raw Variants
gatk CountVariants -V soamtic_variants.vcf.gz
# Result: 311,393

### VEP Annotation 

conda activate vep_env

vep -i somatic_variants_pass.vcf.gz \
    -o somatic_variants_VEP.vcf \
    --vcf --species mus_musculus \
    --cache --dir_cache $HOME/.vep \
    --assembly GRCm39 --everything \
    --fork 8 --force_overwrite


## SSM3 RNA-seq Analysis 
### Fastp Quality Control 

conda activate mouse_env
cd ../SSM3-RNA-seq

# Full quality and length filtering
fastp \
    -i SSM3_RNA_1.fastq \
    -I SSM3_RNA_2.fastq \
    -o SSM3_RNA_1_clean.fastq \
    -O SSM3_RNA_2_clean.fastq \
    -h SSM3_RNA_fastp.html \
    -j SSM3_RNA_fastp.json

# Adapter trimming only (quality and length filtering disabled)
fastp \
    -i SSM3_RNA_1.fastq \
    -I SSM3_RNA_2.fastq \
    -o SSM3_RNA_1_trim.fastq \
    -O SSM3_RNA_2_trim.fastq \
    -Q -L

### Download GTF and Build STAR Index

cd ../Mouse-Resources

# Download GTF
wget https://ftp.ensembl.org/pub/release-115/gtf/mus_musculus/Mus_musculus.GRCm39.115.gtf.gz
gunzip Mus_musculus.GRCm39.115.gtf.gz

# Build STAR genome index (sjdbOverhang = read length - 1 = 125)
STAR --runMode genomeGenerate \
    --genomeDir ../Mouse-Resources/STAR_index \
    --genomeFastaFiles ../Mouse-Resources/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa \
    --sjdbGTFfile ../Mouse-Resources/Mus_musculus.GRCm39.115.gtf \
    --sjdbOverhang 125 \
    --runThreadN 8

### STAR Alignment

cd ../SSM3-RNA-seq

# Raw unfiltered reads
STAR --runMode alignReads \
    --genomeDir ../Mouse-Resources/STAR_index \
    --readFilesIn SSM3_RNA_1.fastq SSM3_RNA_2.fastq \
    --outSAMtype BAM SortedByCoordinate \
    --twopassMode Basic \
    --outSAMattrRGline ID:SSM3_RNA SM:SSM3 PL:ILLUMINA LB:lib1 \
    --runThreadN 8 \
    --outFileNamePrefix SSM3_RNA_NoFastp_

# Adapter trimming only
STAR --runMode alignReads \
    --genomeDir ../Mouse-Resources/STAR_index \
    --readFilesIn SSM3_RNA_1_trim.fastq SSM3_RNA_2_trim.fastq \
    --outSAMtype BAM SortedByCoordinate \
    --twopassMode Basic \
    --outSAMattrRGline ID:SSM3_RNA SM:SSM3 PL:ILLUMINA LB:lib1 \
    --runThreadN 8 \
    --outFileNamePrefix SSM3_RNA_fastpQL_

# Full quality and length filtered (used for downstream analysis)
STAR --runMode alignReads \
    --genomeDir ../Mouse-Resources/STAR_index \
    --readFilesIn SSM3_RNA_1_clean.fastq SSM3_RNA_2_clean.fastq \
    --outSAMtype BAM SortedByCoordinate \
    --twopassMode Basic \
    --outSAMattrRGline ID:SSM3_RNA SM:SSM3 PL:ILLUMINA LB:lib1 \
    --runThreadN 8 \
    --outFileNamePrefix SSM3_RNA_

# Index final BAM
samtools index SSM3_RNA_Aligned.sortedByCoord.out.bam

### Expression Quantificaiotn with StringTie

stringtie SSM3_RNA_Aligned.sortedByCoord.out.bam \
    -G ../Mouse-Resources/Mus_musculus.GRCm39.115.gtf \
    -e \
    -A SSM3_gene_abundance.tsv \
    -o SSM3_stringtie.gtf

### VCF Decomposition

conda activate mouse_env
cd ../Mouse-WGS

vt decompose -s somatic_variants_pass.vcf.gz \
    -o somatic_variants_pass_decomposed.vcf.gz

### Rerun VEP and Plugins on Decomposed VCF

conda activate vep_env

vep -i somatic_variants_pass_decomposed.vcf.gz \
    -o somatic_variants_VEP_plugins_decomposed.vcf \
    --vcf --species mus_musculus \
    --cache --dir_cache $HOME/.vep \
    --assembly GRCm39 --everything \
    --fork 8 --force_overwrite \
    --plugin Wildtype \
    --plugin Frameshift \
    --dir_plugins $HOME/.vep/Plugins

### Generate RNA Readcounts

conda activate mouse_env
cd ../Mouse-WGS

# Download and patch bam_readcount_helper.py
wget https://raw.githubusercontent.com/griffithlab/pmbio.org/refs/heads/master/assets/scripts/bam_readcount_helper.py
sed -i "s|/usr/local/bin/bam-readcount|$(which bam-readcount)|" bam_readcount_helper.py

# Create output directory
mkdir -p Readcounts_RNA

# Run bam_readcount_helper
python bam_readcount_helper.py \
    somatic_variants_pass_decomposed.vcf.gz \
    SSM3 \
    ../Mouse-Resources/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa \
    ../SSM3-RNA-seq/SSM3_RNA_Aligned.sortedByCoord.out.bam \
    ./Readcounts_RNA

### Annotate VCF with RNA Readcounts and Expresison

conda activate vatools_env

# SNV readcounts
vcf-readcount-annotator \
    somatic_variants_VEP_plugins_decomposed.vcf \
    Readcounts_RNA/SSM3_bam_readcount_snv.tsv \
    RNA -s SSM3 -t snv \
    -o SSM3_RNA_SNV_Annotated.vcf

# Indel readcounts
vcf-readcount-annotator \
    SSM3_RNA_SNV_Annotated.vcf \
    Readcounts_RNA/SSM3_bam_readcount_indel.tsv \
    RNA -s SSM3 -t indel \
    -o SSM3_RNA_Annotated.vcf

# Gene expression
vcf-expression-annotator \
    SSM3_RNA_Annotated.vcf \
    ../SSM3-RNA-seq/SSM3_gene_abundance.tsv \
    stringtie gene -s SSM3 \
    -o SSM3_gx_annotated.vcf

# Transcript expression
vcf-expression-annotator \
    SSM3_gx_annotated.vcf \
    ../SSM3-RNA-seq/SSM3_stringtie.gtf \
    stringtie transcript -s SSM3 \
    -o SSM3_final_annotated.vcf


## pVAACseq - WGS 

conda activate pvac_env

# NetMHCpan
pvacseq run somatic_variants_VEP_plugins.vcf SSM3 H-2-Db,H-2-Kb NetMHCpan \
    pvacseq_output/NetMHCpan --top-score-metric=median -e1 8,9,10,11

# NetMHCcons
pvacseq run somatic_variants_VEP_plugins.vcf SSM3 H-2-Db,H-2-Kb NetMHCcons \
    pvacseq_output/NetMHCcons --top-score-metric=median -e1 8,9,10,11

# SMM
pvacseq run somatic_variants_VEP_plugins.vcf SSM3 H-2-Db,H-2-Kb SMM \
    pvacseq_output/SMM --top-score-metric=median -e1 8,9,10,11

# SMMPMBEC
pvacseq run somatic_variants_VEP_plugins.vcf SSM3 H-2-Db,H-2-Kb SMMPMBEC \
    pvacseq_output/SMMPMBEC --top-score-metric=median -e1 8,9,10,11

# Combined
pvacseq run somatic_variants_VEP_plugins.vcf SSM3 H-2-Db,H-2-Kb \
    NetMHCpan NetMHCcons SMM SMMPMBEC \
    pvacseq_output/Combined --top-score-metric=median -e1 8,9,10,11


## pVACseq - Expression

conda activate pvac_env

# NetMHCpan
pvacseq run SSM3_final_annotated.vcf SSM3 H-2-Db,H-2-Kb NetMHCpan \
    pvacseq_output/NetMHCpan_RNA --top-score-metric=median -e1 8,9,10,11

# NetMHCcons
pvacseq run SSM3_final_annotated.vcf SSM3 H-2-Db,H-2-Kb NetMHCcons \
    pvacseq_output/NetMHCcons_RNA --top-score-metric=median -e1 8,9,10,11

# SMM
pvacseq run SSM3_final_annotated.vcf SSM3 H-2-Db,H-2-Kb SMM \
    pvacseq_output/SMM_RNA --top-score-metric=median -e1 8,9,10,11

# SMMPMBEC
pvacseq run SSM3_final_annotated.vcf SSM3 H-2-Db,H-2-Kb SMMPMBEC \
    pvacseq_output/SSMPMBEC_RNA --top-score-metric=median -e1 8,9,10,11

# Combined
pvacseq run SSM3_final_annotated.vcf SSM3 H-2-Db,H-2-Kb \
    NetMHCpan NetMHCcons SMM SMMPMBEC \
    pvacseq_output/Combined_RNA --top-score-metric=median -e1 8,9,10,11


